language: node_js
node_js:
  - '10'

cache:
  yarn: true
  directories:
    - 'node_modules'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

branches:
  only:
    - master

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  - provider: script
    script: 'yarn lerna:publish --yes'
    skip_cleanup: true
    on:
      branch: master
